server:
  port: 8088

spring:
  application:
    name: communication-log-service
  profiles:
    active: dev
  security:
    user:
      name: none
      password: none
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:}

  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
      fail-fast: ${SPRING_CLOUD_CONFIG_FAIL_FAST:false}
      retry:
        initial-interval: 1000
        max-attempts: 6
        multiplier: 1.2
      label: ${SPRING_CLOUD_CONFIG_LABEL:main}

  mail:
    host: smtp.gmail.com
    port: 587
    username: thehieu0814@gmail.com
    password: uzsg awsr wyud xegd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
